# Generated by Django 5.2.7 on 2025-10-05 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0002_auto_20251005_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealassignment',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Ontbijt'), ('lunch', 'Lunch'), ('dinner', 'Diner'), ('snack', 'Tussendoortje'), ('dessert', 'Nagerecht')], help_text='Type of meal (breakfast, lunch, dinner, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='category',
            field=models.CharField(choices=[('produce', 'Groenten & Fruit'), ('meat', 'Vlees & Vis'), ('dairy', 'Zuivel & Eieren'), ('pantry', 'Voorraadkast'), ('frozen', 'Diepvries'), ('bakery', 'Bakkerij'), ('beverages', 'Dranken'), ('condiments', 'Kruiden & Sauzen'), ('spices', 'Specerijen & Kruiden'), ('other', 'Overig')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'start_date'], name='meal_planni_user_id_b7700a_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'end_date'], name='meal_planni_user_id_63bb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'start_date'], name='meal_planni_user_id_21d946_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'end_date'], name='meal_planni_user_id_bd2947_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'generated_at'], name='meal_planni_user_id_453c61_idx'),
        ),
    ]
