# Generated by Django 5.2.7 on 2025-10-05 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0003_alter_mealassignment_meal_type_and_more'),
        ('recipes', '0005_add_nutritional_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPrepSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this meal prep session', max_length=200)),
                ('scheduled_date', models.DateField(help_text='Date when meal prep is scheduled')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.PositiveIntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPrepTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(help_text="Name of the specific task (e.g., 'Chop vegetables', 'Cook rice')", max_length=200)),
                ('estimated_time', models.PositiveIntegerField(blank=True, help_text='Estimated time in minutes', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of execution within the session')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_time', models.PositiveIntegerField(blank=True, help_text='Actual time taken in minutes', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='shoppinglistitem',
            name='meal_planni_purchas_2a9b6d_idx',
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'purchased'], name='meal_planni_shoppin_c2176e_idx'),
        ),
        migrations.AddField(
            model_name='mealprepsession',
            name='user',
            field=models.ForeignKey(help_text='Owner of this meal prep session', on_delete=django.db.models.deletion.CASCADE, related_name='meal_prep_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealpreptask',
            name='meal_prep_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meal_planning.mealprepsession'),
        ),
        migrations.AddField(
            model_name='mealpreptask',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_prep_tasks', to='recipes.recipe'),
        ),
        migrations.AddIndex(
            model_name='mealprepsession',
            index=models.Index(fields=['user', 'scheduled_date'], name='meal_planni_user_id_acbb70_idx'),
        ),
        migrations.AddIndex(
            model_name='mealprepsession',
            index=models.Index(fields=['user', 'status'], name='meal_planni_user_id_2e7369_idx'),
        ),
        migrations.AddIndex(
            model_name='mealprepsession',
            index=models.Index(fields=['scheduled_date'], name='meal_planni_schedul_123df1_idx'),
        ),
        migrations.AddIndex(
            model_name='mealprepsession',
            index=models.Index(fields=['status'], name='meal_planni_status_c39237_idx'),
        ),
        migrations.AddIndex(
            model_name='mealpreptask',
            index=models.Index(fields=['meal_prep_session', 'order'], name='meal_planni_meal_pr_21b6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='mealpreptask',
            index=models.Index(fields=['meal_prep_session', 'completed'], name='meal_planni_meal_pr_19ca94_idx'),
        ),
        migrations.AddIndex(
            model_name='mealpreptask',
            index=models.Index(fields=['recipe'], name='meal_planni_recipe__ae21d8_idx'),
        ),
    ]
