# Generated by Django 5.2.7 on 2025-10-05 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('meal_planning', '0004_add_meal_prep_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Family this meal plan belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='families.family'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this meal plan is shared with family members'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='shared_with_family',
            field=models.BooleanField(default=True, help_text='Share with all family members (when is_shared=True)'),
        ),
        migrations.AddField(
            model_name='mealprepsession',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Family this meal prep session belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_prep_sessions', to='families.family'),
        ),
        migrations.AddField(
            model_name='mealprepsession',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this meal prep session is shared with family members'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Family this shopping list belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='families.family'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this shopping list is shared with family members'),
        ),
    ]
