[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci']

[phases.build]
dependsOn = ['install']
cmds = ['npm run build']

[start]
cmd = 'npx serve dist/spa -s -l $PORT'