[phases.setup]
nixPkgs = ['python312']

[phases.install]
dependsOn = ['setup']
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn recipe_meal_planner.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 2'