[phases.setup]
nixPkgs = ['python39']

[phases.install]
dependsOn = ['setup']
cmds = ['pip install -r requirements.txt']

[phases.build]
dependsOn = ['install']
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'python manage.py migrate && gunicorn recipe_meal_planner.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 2'