# Generated by Django 5.2.7 on 2025-10-05 11:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Family name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Family description')),
                ('default_servings', models.PositiveIntegerField(default=4, help_text='Default number of servings for meal plans', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('meal_planning_start_day', models.CharField(choices=[('monday', 'Maandag'), ('sunday', 'Zondag'), ('saturday', 'Zaterdag')], default='monday', help_text='Day of the week to start meal planning', max_length=10)),
                ('shopping_day', models.CharField(choices=[('monday', 'Maandag'), ('tuesday', 'Dinsdag'), ('wednesday', 'Woensdag'), ('thursday', 'Donderdag'), ('friday', 'Vrijdag'), ('saturday', 'Zaterdag'), ('sunday', 'Zondag')], default='saturday', help_text='Preferred shopping day', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of invitee', max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Beheerder'), ('member', 'Lid'), ('viewer', 'Kijker')], default='member', help_text='Role to assign when invitation is accepted', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('accepted', 'Geaccepteerd'), ('declined', 'Afgewezen'), ('expired', 'Verlopen')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message to include with invitation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When invitation expires')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='families.family')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('family', 'email')},
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Beheerder'), ('member', 'Lid'), ('viewer', 'Kijker')], default='member', help_text='Role within the family', max_length=10)),
                ('can_create_meal_plans', models.BooleanField(default=True, help_text='Can create and edit meal plans')),
                ('can_manage_recipes', models.BooleanField(default=True, help_text='Can create and edit recipes')),
                ('can_manage_shopping_lists', models.BooleanField(default=True, help_text='Can create and edit shopping lists')),
                ('can_invite_members', models.BooleanField(default=False, help_text='Can invite new family members')),
                ('dietary_restrictions', models.JSONField(default=list, help_text='List of dietary restrictions')),
                ('favorite_cuisines', models.JSONField(default=list, help_text='List of favorite cuisines')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__first_name', 'user__username'],
                'unique_together': {('family', 'user')},
            },
        ),
    ]
