# Generated by Django 5.2.7 on 2025-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of family member (for child accounts)', null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='can_suggest_meals',
            field=models.BooleanField(default=True, help_text='Can suggest meals for meal planning'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='can_view_all_recipes',
            field=models.BooleanField(default=True, help_text='Can view all family recipes'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='parental_controls',
            field=models.BooleanField(default=False, help_text='Enable parental controls for this member'),
        ),
        migrations.AlterField(
            model_name='familyinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Beheerder'), ('member', 'Lid'), ('child', 'Kind'), ('viewer', 'Kijker')], default='member', help_text='Role to assign when invitation is accepted', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Beheerder'), ('member', 'Lid'), ('child', 'Kind'), ('viewer', 'Kijker')], default='member', help_text='Role within the family', max_length=10),
        ),
    ]
