# Generated by Django 5.2.7 on 2025-10-04 18:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name for this meal plan (e.g., 'Week of Jan 15')", max_length=200)),
                ('start_date', models.DateField(help_text='Start date of the meal plan')),
                ('end_date', models.DateField(help_text='End date of the meal plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='meal_planni_start_d_d710c8_idx'), models.Index(fields=['end_date'], name='meal_planni_end_dat_0954b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMeals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date for these meals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='meal_planning.mealplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this shopping list', max_length=200)),
                ('start_date', models.DateField(help_text='Start date for meal plans to include')),
                ('end_date', models.DateField(help_text='End date for meal plans to include')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meal_plans', models.ManyToManyField(help_text='Meal plans included in this shopping list', related_name='shopping_lists', to='meal_planning.mealplan')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('total_amount', models.CharField(help_text='Consolidated amount needed', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('PRODUCE', 'Produce'), ('MEAT', 'Meat'), ('DAIRY', 'Dairy'), ('PANTRY', 'Pantry'), ('FROZEN', 'Frozen'), ('BAKERY', 'Bakery'), ('BEVERAGES', 'Beverages'), ('CONDIMENTS', 'Condiments'), ('SPICES', 'Spices'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('purchased', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal_planning.shoppinglist')),
                ('source_recipes', models.ManyToManyField(help_text='Recipes that contributed to this shopping list item', related_name='shopping_list_items', to='recipes.recipe')),
            ],
            options={
                'ordering': ['category', 'ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='MealAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert')], help_text='Type of meal (breakfast, lunch, dinner, etc.)', max_length=20)),
                ('servings_planned', models.PositiveIntegerField(blank=True, help_text='Number of servings planned (overrides recipe default)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this meal assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_assignments', to='meal_planning.dailymeals')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_assignments', to='recipes.recipe')),
            ],
            options={
                'ordering': ['daily_meals__date', 'meal_type'],
                'indexes': [models.Index(fields=['daily_meals', 'meal_type'], name='meal_planni_daily_m_0fe5c5_idx'), models.Index(fields=['recipe'], name='meal_planni_recipe__5e5472_idx')],
                'unique_together': {('daily_meals', 'meal_type', 'recipe')},
            },
        ),
        migrations.AddIndex(
            model_name='dailymeals',
            index=models.Index(fields=['meal_plan', 'date'], name='meal_planni_meal_pl_4e4382_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymeals',
            index=models.Index(fields=['date'], name='meal_planni_date_d0be48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymeals',
            unique_together={('meal_plan', 'date')},
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['start_date'], name='meal_planni_start_d_e09999_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['end_date'], name='meal_planni_end_dat_4f2c12_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['generated_at'], name='meal_planni_generat_b26372_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'category'], name='meal_planni_shoppin_bcc0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['ingredient_name'], name='meal_planni_ingredi_66e446_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['purchased'], name='meal_planni_purchas_2a9b6d_idx'),
        ),
    ]
