# Generated by Django 5.2.7 on 2025-10-05 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(
                default=1,
                help_text='Owner of this meal plan',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='meal_plans',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(
                default=1,
                help_text='Owner of this shopping list',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shopping_lists',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
