# Generated by Django 5.2.7 on 2025-10-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Recipe image', null=True, upload_to='recipe_images/'),
        ),
    ]
