# Generated by Django 5.2.7 on 2025-10-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_nutritional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Recipe image (max 5MB, JPG/PNG/WebP)', null=True, upload_to='recipe_images/%Y/%m/'),
        ),
    ]
