# Generated by Django 5.2.7 on 2025-10-05 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20251005_0007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('produce', 'Groenten & Fruit'), ('meat', 'Vlees & Vis'), ('dairy', 'Zuivel & Eieren'), ('pantry', 'Voorraadkast'), ('frozen', 'Diepvries'), ('bakery', 'Bakkerij'), ('beverages', 'Dranken'), ('condiments', 'Kruiden & Sauzen'), ('spices', 'Specerijen & Kruiden'), ('other', 'Overig')], default='other', help_text='Ingredient category for shopping list organization', max_length=20),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['user', 'title'], name='recipes_rec_user_id_4f25eb_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['user', 'source'], name='recipes_rec_user_id_155e18_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['user', 'created_at'], name='recipes_rec_user_id_5244dd_idx'),
        ),
    ]
