# Generated by Django 5.2.7 on 2025-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates in grams per serving', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fat in grams per serving', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams per serving', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein in grams per serving', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sodium in milligrams per serving', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sugar in grams per serving', max_digits=6, null=True),
        ),
    ]
