# Generated by Django 5.2.7 on 2025-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_shared_with_family',
            field=models.BooleanField(default=False, help_text='Whether this recipe is shared with family members'),
        ),
    ]
