# Generated by Django 5.2.7 on 2025-10-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_add_family_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(choices=[('pdf', 'PDF Import'), ('image', 'Image Import'), ('manual', 'Manual Entry'), ('database', 'Database Import')], default='manual', help_text='Source of the recipe', max_length=20),
        ),
    ]
