# Generated by Django 5.2.7 on 2025-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_add_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(blank=True, help_text="Amount (e.g., '2 cups', '1 tbsp')", max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Ingredient name', max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.CharField(blank=True, help_text="Additional notes (e.g., 'chopped', 'optional')", max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Recipe title', max_length=500),
        ),
    ]
