# Generated by Django 5.2.7 on 2025-11-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredient_amount_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(blank=True, help_text="Amount (e.g., '2 cups', '1 tbsp')", max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Ingredient name', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.CharField(blank=True, help_text="Additional notes (e.g., 'chopped', 'optional')", max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(help_text='Recipe title', max_length=1000),
        ),
    ]
